Repository Stock-Management-System/dentalApp, pull requests merged in 2022-12, with the labels that each got.

#50 Rontgen page pop up modify
  src/components/polyclinic/NavBar.jsx
  src/components/polyclinic/rontgen/ImageModal.jsx
  src/components/polyclinic/rontgen/Modal.jsx
  src/components/polyclinic/rontgen/ModalExamineRontgen.jsx
  src/components/polyclinic/rontgen/RontgenQuery.jsx
Labels: enhancement

#51 Dashboard navbar
  src/assets/dashboardIntro.png
  src/assets/dashboard_calendar.png
  src/assets/dashboard_clinic.png
  src/assets/dashboard_doctor.png
  src/assets/dashboard_intro.png
  src/components/dashboard/Footer.jsx
  src/components/dashboard/Modal.jsx
  src/components/dashboard/NavBar.jsx
  src/components/doctor/Sidebar.jsx
  src/components/polyclinic/Sidebar.jsx
  src/index.css
  src/pages/dashboard/MainPage.jsx
  src/router/AppRouter.jsx
  tailwind.config.js
Labels: enhancement

#59 fixed
  src/components/polyclinic/rontgen/Modal.jsx
  src/components/polyclinic/rontgen/ModalExamineRontgen.jsx
  src/components/polyclinic/rontgen/RontgenQuery.jsx
Labels: bug

#57 Past transaction page
  src/components/polyclinic/pastTransaction/PastTransaction.jsx
  src/components/polyclinic/pastTransaction/QueryWithIdentityNo.jsx
  src/components/polyclinic/pastTransaction/QueryWithPersonalInfo.jsx
  src/pages/polyclinic/operations/Operations.jsx
Labels: enhancement

#64 Login register
  src/components/dashboard/ForgotPassword.jsx
  src/components/dashboard/LoginModal.jsx
  src/components/dashboard/NavBar.jsx
  src/components/dashboard/RegisterModal.jsx
  src/helpers/ilData.js
  src/pages/dashboard/MainPage.jsx
  tailwind.config.js
Labels: dashboard

#68 Login-register-update
  src/components/dashboard/ForgotPassword.jsx
  src/components/dashboard/LoginModal.jsx
  src/components/dashboard/Modal.jsx
  src/components/dashboard/NavBar.jsx
  src/components/dashboard/RegisterModal.jsx
  src/pages/dashboard/MainPage.jsx
Labels: dashboard

#69 Main-page-modals-bugs
  src/components/dashboard/ForgotPassword.jsx
  src/components/dashboard/LoginModal.jsx
  src/components/dashboard/RegisterModal.jsx
  src/index.css
Labels: bug

#60 appointments data
  src/components/polyclinic/Appointments.jsx
  src/components/polyclinic/MiddleLink.jsx
  src/components/polyclinic/appointments/DateRange.jsx
  src/components/polyclinic/appointments/DoctorsAppointments.jsx
  src/components/polyclinic/appointments/PatientsAppointments.jsx
  src/components/polyclinic/appointments/TodayAppointments.jsx
  src/helpers/data.js
Labels: Polyclinic

#66 Add appointments pop up
  src/components/polyclinic/Appointments.jsx
  src/components/polyclinic/addAppointmentsModal/AddAppointmentsModal.jsx
  src/components/polyclinic/addAppointmentsModal/AddAppointmentsModalForXsNav.jsx
  src/components/polyclinic/addAppointmentsModal/FirstStepAddAppointment.jsx
  src/components/polyclinic/addAppointmentsModal/SecondStepAddAppointment.jsx
  src/components/polyclinic/addAppointmentsModal/ThirdStepAddAppointment.jsx
  src/components/polyclinic/layout/Layout.jsx
  src/components/polyclinic/layout/NavBar.jsx
  src/components/polyclinic/layout/Sidebar.jsx
  src/components/polyclinic/polyclinicDashboard/ClinicHeader.jsx
  src/components/polyclinic/polyclinicDashboard/Container.jsx
  src/components/polyclinic/polyclinicDashboard/MiddleLink.jsx
  src/pages/polyclinic/account/Account.jsx
  src/pages/polyclinic/appointments/PolyclinicAppointments.jsx
  src/pages/polyclinic/doctors/PolyclinicDoctors.jsx
  src/pages/polyclinic/operations/Operations.jsx
  src/pages/polyclinic/patients/Patients.jsx
  src/pages/polyclinic/profile/PolyclinicProfile.jsx
  src/pages/polyclinic/rontgen/Rontgen.jsx
  src/pages/polyclinic/settings/Settings.jsx
Labels: enhancement

#72 Account financial management
  src/components/polyclinic/accountFinancial/addAccount/AddFinancialAccount.jsx
  src/components/polyclinic/accountFinancial/addAccount/AddFinancialForm.jsx
  src/components/polyclinic/accountFinancial/addAccount/AddFinancialPatientInfo.jsx
  src/components/polyclinic/accountFinancial/addAccount/PatientInformation.jsx
  src/components/polyclinic/accountFinancial/collection/Collection.jsx
  src/components/polyclinic/accountFinancial/collection/CollectionInfo.jsx
  src/pages/polyclinic/account/Account.jsx
Labels: enhancement

#75 added polyclinic doctors cards
  src/components/polyclinic/polyclinicDashboard/DoctorsCard.jsx
  src/components/polyclinic/polyclinicDashboard/DoctorsTitle.jsx
  src/pages/polyclinic/profile/PolyclinicProfile.jsx
Labels: dashboard

#76 Account(Financial) Management Report Add
  src/pages/polyclinic/account/Account.jsx
Labels: Polyclinic

#81 Bug-Fixed
  src/pages/polyclinic/account/Account.jsx
Labels: bug

#79 fixed
  src/components/polyclinic/accountFinancial/report/Report.jsx
  src/components/polyclinic/accountFinancial/report/ReportInfo.jsx
  src/pages/polyclinic/account/Account.jsx
  src/pages/polyclinic/patients/Patients.jsx
Labels: bug

#86 Doctor patient new record
  .vscode/settings.json
  src/components/doctor/Navbar.jsx
  src/components/doctor/doctorDashboard/DoctorHeader.jsx
  src/components/doctor/patient/AddPatientModal.jsx
  src/pages/doctor/patients/Patients.jsx
Labels: enhancement
