Repository Stock-Management-System/dentalApp, pull requests merged in 2022-11, with the labels that each got.

#34 link added in Sidebar
  src/components/polyclinic/Sidebar.jsx
Labels: enhancement

#41 Footer
  src/components/polyclinic/Footer.jsx
  src/index.css
  src/router/AppRouter.jsx
  tailwind.config.js
Labels: good first issue

#40 Rontgen popup
  package.json
  postcss.config.js
  src/components/polyclinic/rontgen/Modal.jsx
  src/components/polyclinic/rontgen/ModalExamineRontgen.jsx
  src/components/polyclinic/rontgen/RontgenQuery.jsx
  src/pages/polyclinic/rontgen/Rontgen.jsx
  tailwind.config.js
  yarn.lock
Labels: enhancement

#47 Poliyclinic page structure
  src/components/dashboard/Footer.jsx
  src/components/doctor/Layout.jsx
  src/components/doctor/Navbar.jsx
  src/components/doctor/Sidebar.jsx
  src/components/polyclinic/Sidebar.jsx
  src/pages/dashboard/MainPage.jsx
  src/pages/doctor/appointments/Appointments.jsx
  src/pages/doctor/appointments/appointments.scss
  src/pages/doctor/patients/Patients.jsx
  src/pages/doctor/patients/patients.scss
  src/pages/doctor/profile/DoctorProfile.jsx
  src/pages/doctor/profile/doctorProfile.scss
  src/pages/doctor/settings/DoctorSettings.jsx
  src/pages/doctor/settings/doctorSettings.scss
  src/pages/polyclinic/account/Account.jsx
  src/pages/polyclinic/account/account.scss
  src/pages/polyclinic/appointments/PolyclinicAppointments.jsx
  src/pages/polyclinic/appointments/PolyclinicAppointments.scss
  src/pages/polyclinic/doctors/polyclinicDoctors.scss
  src/pages/polyclinic/operations/Operations.jsx
  src/pages/polyclinic/operations/operations.scss
  src/pages/polyclinic/patients/Patients.jsx
  src/pages/polyclinic/patients/patients.scss
  src/pages/polyclinic/profile/PolyclinicProfile.jsx
  src/pages/polyclinic/profile/polyclinicProfile.scss
  src/pages/polyclinic/rontgen/Rontgen.jsx
  src/pages/polyclinic/rontgen/rontgen.scss
  src/pages/polyclinic/settings/Settings.jsx
  src/router/AppRouter.jsx
Labels: enhancement

#48 doctor permonce comp.
  src/assets/sinusgraphic.png
  src/components/polyclinic/doctors/DoctorInformation.jsx
  src/components/polyclinic/doctors/DoctorIstatistik.jsx
  src/components/polyclinic/doctors/DoctorPerformance.jsx
  src/components/polyclinic/doctors/DoctorTreatments.jsx
  src/helpers/data.js
  src/pages/polyclinic/doctors/PolyclinicDoctors.jsx
Labels: Polyclinic
